name: win-build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        arch: [x64] #, arm64]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true    
    
    steps:
    - uses: actions/checkout@v4

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 3.0.0
        actions-cache-folder: '.xmake-cache'

    - name: configure
      shell: cmd
      run: |
        xmake f -c -y -vD --mqtt=y

    - name: build_rest_server
      shell: cmd
      run: |
        xmake -bvD rest_server

    - name: build_node_server
      shell: cmd
      run: |
        xmake -bvD node_server

    - name: build_websocket_server
      shell: cmd
      run: |
        xmake -bvD websocket_server

    - name: build_mqtt_broker
      shell: cmd
      run: |
        xmake -bvD mqtt_broker
        